Form validation
frontend-park-mail-ru/2020_1_k-on pull request #10
Opened 2020-02-18 15:24 UTC by DronBrigadir

2020-02-18 19:46 UTC, n-merkulova reviewed
Лучше вынеси валидацию разных инпутов в разные функции, которые возвращали бы boolean

2020-02-18 19:46 UTC, n-merkulova commented on static/js/validation.js
> +        password_error.textContent = 'Пароль должен содержать 1 заглавную букву, 1 строчную букву и одну цифру,' +
Вместо конкатенации строк можно использовать бэктики ([чек](https://jack.ofspades.com/multiline-strings-in-es6-javascript/))

2020-02-18 19:46 UTC, crueltycute commented on static/js/validation.js
> +        login_error.textContent = 'Логин должен содержать от 4 до 15 символов и состоять из цифр и латинских символов';
Вынеси сообщения об ошибках в константы

2020-02-18 19:46 UTC, crueltycute commented on static/js/validation.js
> +        password.style.border = '1px solid red';
стиль тоже можно вынести в константу

2020-02-18 19:46 UTC, crueltycute commented on static/js/validation.js
> +    const password = document.querySelector('.auth-form__input_password');
Тебе необязательно делать поиск в document, можно искать в элементе формы

2020-02-18 19:46 UTC, crueltycute commented on static/js/validation.js
> +    const login_error = document.querySelector('.auth-form__input_login ~ .auth-form__error');
Нифига загнул
Зачем так сложно?
Можно вообще этим элементам просто айдишники поставить

2020-02-19 10:05 UTC, n-merkulova reviewed
осталось обернуть в функцию

2020-02-19 10:05 UTC, n-merkulova commented on static/js/validation.js
> +        if (inputItem == null) {
ааааа нестрогое сравнение...

2020-02-19 10:05 UTC, n-merkulova commented on static/js/validation.js
> +        const inputRegex = RegExp(value.regex);
ты по идее можешь в объекте сразу хранить RegExp, а не строку

2020-02-19 19:24 UTC, n-merkulova requested changes
жду реализацию через классы

2020-02-21 07:45 UTC, n-merkulova requested changes

2020-02-21 07:45 UTC, n-merkulova commented on server.js
> +app.get('/spa', (req, res) => {
это че еще такое ммм?

2020-02-21 07:45 UTC, crueltycute commented on static/js/Input.js
> +class Input {
можно сразу записать `export default class Input`

2020-02-21 07:45 UTC, crueltycute commented on static/js/Input.js
> +    'auth-form__input auth-form__input_login': {
Зачем тебе портянка из className'ов, если у тебя есть айдишники на инпутах? Лучше сделай по айди

2020-02-21 07:45 UTC, crueltycute commented on static/js/Input.js
> +            '^[a-zA-Z][a-zA-Z0-9-_.]{4,15}$'
Запиши в одну строку так:`regex: /^[a-zA-Z][a-zA-Z0-9-_.]{4,15}$/,`

2020-02-21 07:45 UTC, crueltycute commented on static/js/Input.js
> +const inputOptions = {
такие константы лучше писать капсом
`const INPUTS = ...`

2020-02-21 07:45 UTC, crueltycute commented on static/js/validation.js
> +        const inputs = form.getElementsByTagName('input');
возможно, здесь логичнее `const inputs = form.getElementsByClassName('.auth-form__input');`

2020-02-21 07:45 UTC, crueltycute commented on static/js/validation.js
> +            const inputClassItem = new Input(inputItem.className);
переделай на айдишники

2020-02-21 07:45 UTC, crueltycute commented on static/js/validation.js
> +            const inputError = form.querySelector(`#${inputClassItem.errorID}`);
здесь `getElementById`

2020-02-21 07:45 UTC, crueltycute commented on static/js/validation.js
> +            if (!inputClassItem.regex.test(inputItem.value)) {
чуть выше можно сделать `isValidationError = !inputClassItem.regex.test(inputItem.value);` и тогда в ифчике будет читабельнее `if (isValidationError)`, мне кажется

2020-02-21 09:44 UTC, DronBrigadir commented on server.js
> +app.get('/spa', (req, res) => {
хз, я отменил merge этот, у меня на локальном этого нет

2020-02-21 10:00 UTC, DronBrigadir commented on static/js/validation.js
> +            if (!inputClassItem.regex.test(inputItem.value)) {
я так сделал, чтобы isValidationError сохранился, просто если первый input будет ошибочный, а второй нет, то флаг этот сбросится

2020-02-21 10:50 UTC, n-merkulova approved these changes

2020-02-21 10:51 UTC, merged