Router
frontend-park-mail-ru/2020_1_k-on pull request #15
Opened 2020-02-25 09:44 UTC by DronBrigadir

2020-02-25 16:14 UTC, n-merkulova requested changes
есть к тебе вопросы
и некоторые замечания
и еще хочу от тебя JSDoc

2020-02-25 16:14 UTC, n-merkulova commented on static/js/libs/router.js
> +        window.addEventListener('popstate', () => {
Расскажи, что за событие popstate и когда оно вызывается

2020-02-25 16:14 UTC, n-merkulova commented on static/js/libs/validation.js
> +import Input from './input';
Имена классов с большой буквы

2020-02-25 16:14 UTC, crueltycute commented on static/js/libs/router.js
> +        document.addEventListener('click', (evt) => {
Почему вешаешь eventListener на document?

2020-02-25 16:14 UTC, crueltycute commented on static/js/index.js
>  import ProfileController from './controllers/profileController';
возможно, сам файл лучше назвать не index, а App

2020-02-25 16:14 UTC, crueltycute commented on static/js/index.js
> +    router.add('/login', container, controllers.login.view);
поле container одинаковое
можно сделать его третьим параметром и поставить ему значение по умолчанию
а можно вообще не передавать

2020-02-25 16:14 UTC, crueltycute commented on static/js/index.js
>          index: new IndexController(),
index название не оч, придумай что-то более говорящее

2020-02-25 16:14 UTC, crueltycute commented on static/js/libs/router.js
> +        this.routes = new Map();
почему хранишь пути именно в мапе?

2020-02-25 16:14 UTC, crueltycute commented on static/js/libs/router.js
> +    constructor(root) {
писала уже, что container в root прокидывать необязательно, как по мне

2020-02-25 16:14 UTC, crueltycute commented on static/js/libs/router.js
> +    add(path, root = this.root, view) {
а, так у тебя здесь уже стоит даже параметр по умолчанию...
точно прокидывать container не нужно в add

2020-02-25 20:13 UTC, DronBrigadir commented on static/js/libs/router.js
> +        window.addEventListener('popstate', () => {
когда переходишь по истории назад или вперед по кнопкам в браузере

2020-02-25 20:15 UTC, DronBrigadir commented on static/js/libs/router.js
> +        document.addEventListener('click', (evt) => {
потому что у меня два блока body и header, в роутер в качестве корня я передаю body

2020-02-25 20:16 UTC, DronBrigadir commented on static/js/libs/router.js
> +        this.routes = new Map();
удобней проверять существующий маршрут

2020-02-26 06:52 UTC, crueltycute commented on static/js/libs/router.js
> +        document.addEventListener('click', (evt) => {
Header и body - неудачные названия, посмотри структуру html 
Header лучше изменить на navbar
Плюс ты передаешь не body, а container
А обработчик вешаешь на document

2020-02-26 07:18 UTC, DronBrigadir commented on static/js/libs/router.js
> +        document.addEventListener('click', (evt) => {
у меня 2 div в боди с id header и container, в header я рендерю navbar, а container передаю в качестве корня для роутера и чтобы отслеживать клики по ссылкам в navbar, я повесил обработчик на документ

2020-02-26 07:23 UTC, n-merkulova approved these changes

2020-02-26 07:26 UTC, merged