Layout
frontend-park-mail-ru/2020_1_k-on pull request #24
Opened 2020-03-05 21:21 UTC by DronBrigadir

Логин + регистрация, поправил навбар, чтобы его не пидорасило

2020-03-06 08:33 UTC, n-merkulova requested changes

2020-03-06 08:33 UTC, crueltycute commented on static/css/form.scss
> +  padding: 14px 14px;
просто `padding: 14px;`

2020-03-06 08:33 UTC, crueltycute commented on static/js/libs/passwordToggler.js
> +    if (password.type === 'password') {
можно записать короче тернаркой

2020-03-06 08:33 UTC, crueltycute commented on static/js/views/loginView/loginView.js
> +            'form__eye'
зачем перенос на новую строку?

2020-03-06 08:33 UTC, crueltycute commented on static/js/views/loginView/loginView.tmpl.xml
> +                           type="text" id="login" minlength="4" maxlength="15"
кстати максимальная длина пароля не оч стратегия, лучше maxlength выпилить везде

2020-03-07 18:18 UTC, n-merkulova approved these changes
комменты некритичны, можешь править, а можешь нет
надо смержить в дев и раскатить на тачку, а то верстку трудно ревьюить, когда не видишь, как выглядит

2020-03-07 18:18 UTC, crueltycute commented on static/css/form.scss
> +  position: absolute;
чет мне кажется тут вполне можно было сделать без абсолютного позиционирования

2020-03-07 18:18 UTC, crueltycute commented on static/css/form.scss
> +  position: absolute;
и тут тоже

2020-03-07 18:18 UTC, crueltycute commented on static/js/views/loginView/loginView.scss
> +  position: absolute;
и тут зачем абсолют?

2020-03-07 18:18 UTC, crueltycute commented on static/js/views/loginView/loginView.scss
> +  background-size: 100% 100%;
background-size: cover мб? почитай вообще, какие параметры у background кстати

2020-03-07 18:18 UTC, crueltycute commented on static/js/views/loginView/loginView.tmpl.xml
> +                    <img class="form__eye" src="/static/img/eye.svg"/>
лучше было бы сделать фоном картинку, как мне кажется, а не тегом img

2020-03-08 13:46 UTC, DronBrigadir commented on static/js/views/loginView/loginView.scss
> +  background-size: 100% 100%;
с cover он как-то картинку не ровно ставит, смещает как-то

2020-03-08 13:48 UTC, merged