Navbar auth change
frontend-park-mail-ru/2020_1_k-on pull request #25
Opened 2020-03-06 15:30 UTC by DronBrigadir

2020-03-07 18:47 UTC, n-merkulova requested changes
вроде нормас, но надо бы уже события шин вынести в константы

2020-03-07 18:47 UTC, crueltycute commented on static/js/app.js
> +        signup: new SignUpController(router, globalEventBus),
тебе надо будет прокидывать ее во все контроллеры
нужно, чтоб разлогиниться можно было с любой страницы

2020-03-07 18:47 UTC, crueltycute commented on static/js/components/navbar/navbar.js
> +            'login': 'Авторизация',
айтемы навбара тоже можно вынести в константы в отдельную мапку

2020-03-07 18:47 UTC, crueltycute commented on static/js/components/navbar/navbar.js
> +            'renderForAuth',
все события для всех шин событий надо вынести в константы, создай мапку для каждой шины

2020-03-07 18:47 UTC, crueltycute commented on static/js/components/navbar/navbar.tmpl.xml
> +<!--            <fest:each iterate="items" index="url" value="name">-->
зачем тут эти коменты?

2020-03-07 18:47 UTC, crueltycute commented on static/js/controllers/loginController.js
> +                this.globalEventBus.publish('renderForAuth');
колбэки на события тоже можно в мапку константную запихнуть

2020-03-07 18:47 UTC, crueltycute commented on static/js/libs/api.js
> +            url: '/logout',
это че, объясни

2020-03-07 18:47 UTC, crueltycute commented on static/js/libs/network.js
> +    static doDelete({host = SERVER_ADDRESS, url = '/'} = {}) {
и это

2020-03-08 12:50 UTC, DronBrigadir commented on static/js/app.js
> +        signup: new SignUpController(router, globalEventBus),
так разлогиниться можно с любой страницы, я в эти прокинул, чтобы навбар менять для авторизованного пользователя после логина и регистрации

2020-03-08 12:51 UTC, DronBrigadir commented on static/js/libs/api.js
> +            url: '/logout',
отправочка запроса на логаут пользователя

2020-03-08 12:52 UTC, DronBrigadir commented on static/js/libs/network.js
> +    static doDelete({host = SERVER_ADDRESS, url = '/'} = {}) {
отправочка запроса DELETE на сервер

2020-03-08 13:44 UTC, merged