New movie page + index page
frontend-park-mail-ru/2020_1_k-on pull request #27
Opened 2020-03-12 20:11 UTC by AliceSitedge

2020-03-13 16:45 UTC, n-merkulova requested changes
Все супер, только надо решить мерж конфликты и маленькие замечания в стилях подправить

2020-03-13 16:45 UTC, n-merkulova commented on static/css/style.scss
> +  padding-left: $paragraph;
Можно записать в одну строчку: padding: 0 $paragraph;

2020-03-13 16:45 UTC, n-merkulova commented on static/css/style.scss
> +  background-position: center;
Background тоже записывается в одну строчку, кажется, как-то так: background: no-repeat center 0 / cover

2020-03-13 16:45 UTC, n-merkulova commented on static/css/variables.scss
> +  src: url('../fonts/Montserrat-Medium.ttf')
Андрей в соседней ветке создал файл для шрифтов, надо будет вынести их туда, когда смержитесь
Плюс, раз много разных шрифтов и вы верстаете вдвоем, для удобства можно их обозначать константами - например, что-то вроде $headers-font

2020-03-13 16:45 UTC, n-merkulova commented on static/img/down-arrow-active.svg
> +<g>
Иконки svg лучше сжимать, для этого есть разные сервисы, которые чистят код внутри файла .svg от всего лишнего
Например, можно использовать svgminify.com

2020-03-13 16:45 UTC, n-merkulova commented on static/js/components/navbar/navbar.scss
> +  //padding: 0.7em 1em 0.7em 0;
Комменты лучше не оставлять

2020-03-13 16:45 UTC, n-merkulova commented on static/js/components/navbar/navbar.tmpl.xml
> +<!--            <form class="navbar__search-form">-->
Комменты

2020-03-13 16:45 UTC, n-merkulova commented on static/js/views/indexView/indexView.scss
> +  background-position: center;
Используй сокращённую запись

2020-03-13 16:45 UTC, n-merkulova commented on static/js/views/indexView/indexView.scss
> +  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
Цвет в константы

2020-03-13 16:45 UTC, n-merkulova commented on static/js/views/movieView/movieView.js
> +    description: 'Мини-сериал от режиссера «Большой маленькой лжи» Жан-Марка Валле, ' +
Для длинных строк, чтобы избежать конкатенации, приятнее использовать бэктики

2020-03-13 16:45 UTC, n-merkulova commented on static/js/views/movieView/movieView.scss
> +  width: 35px;
Можно написать миксин типа 
@include square($side)
Вообще изучи миксины, очень-очень классная штука

2020-03-13 16:45 UTC, crueltycute commented on static/js/views/movieView/movieView.tmpl.xml
> +<!--                <div class="add-to-list-block">-->
Комменты

2020-03-15 16:54 UTC, AliceSitedge commented on static/css/style.scss
> +  padding-left: $paragraph;
Тогда отступы по вертикали нельзя будет поставить другие, а я в некоторых местах их ставлю

2020-03-15 16:57 UTC, AliceSitedge commented on static/js/components/navbar/navbar.tmpl.xml
> +<!--            <form class="navbar__search-form">-->
Я временно убрала этот элемент, пока он не работает. Или все равно лучше удалить?

2020-03-15 16:57 UTC, AliceSitedge commented on static/js/views/movieView/movieView.tmpl.xml
> +<!--                <div class="add-to-list-block">-->
Здесь так же

2020-03-15 20:19 UTC, n-merkulova approved these changes
Замечания необязательно поправлять, это просто как рекомендации на будущее скорее
Можно мержить, все ок

2020-03-15 20:19 UTC, crueltycute commented on static/css/mixins.scss
> +@mixin center-position {
Вот это класс

2020-03-15 20:19 UTC, crueltycute commented on static/css/style.scss
> +  background: no-repeat center / cover;
Можно будет еще сделать миксин на background, кстати

2020-03-15 20:19 UTC, crueltycute commented on static/js/views/movieView/movieView.scss
> +@import '../../../css/mixins';
Можно добавить в вебпак алиас на директорию с общими стилями, чтобы не писать длинно '../../..'
Было бы просто `@import '~css/mixins'`

2020-03-15 20:19 UTC, crueltycute commented on static/js/views/profileView/profileView.scss
> +  background-image: url(/static/img/avatar.jpg);
куда кавычки пропали?(

2020-03-16 09:22 UTC, AliceSitedge commented on static/js/views/profileView/profileView.scss
> +  background-image: url(/static/img/avatar.jpg);
Без них тоже работает, и в ide'шке красиво синеньким подсвечивается

2020-03-16 09:23 UTC, merged