Index page
frontend-park-mail-ru/2020_1_k-on pull request #31
Opened 2020-03-21 14:43 UTC by DronBrigadir

2020-03-22 10:14 UTC, n-merkulova requested changes

2020-03-22 10:14 UTC, n-merkulova commented on static/js/views/indexView/indexView.scss
> +  margin-bottom: -8%;
Зачем? Вроде и без этого выглядит ок
Не усложняй лучше, а то с мобильной версткой только намучаешься

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +  height: 48vw;
Что за практика задавать высоту через единицы измерения ширины?)
vh или пиксели

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +      &:hover {
Дублируется одинаковый код два раза
:hover одинаковый для обеих стрелок, подними просто в &__arrows

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +    bottom: 28%;
Многовато, мне кажется
Лучше сильнее прижать к низу, выбери сам значение bottom <= 10%
Можно даже в пикселях, как left сделал

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +      font-family: Montserrat-Medium;
Дублируешь шрифт, повесь его просто на &__content

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +    &_title {
У тебя получается не совсем бэм
title, description - это скорее элементы, не модификаторы
Можно было бы прописать так:
&-content {
  &__title {...}
  &__description {...}
}

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +  &__bottom-shade {
Этот элемент и верхний можно написать короче, чтоб не дублировались стили
&__shade {
  // здесь стили одинаковые для двух элементов
  &_left { 
  // стили уникальные для left
  }
  &_right {
  // стили уникальные для right
  }
}

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +      text-align: justify;
Проверь на caniuse.com поддержку в браузерах
Если низкая, замени

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +.invisible {
Ору с названия, сори
Почему не hidden?

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +    scroll-behavior: smooth;
У этого тоже низкая поддержка браузерами, кстати говоря

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +  &__arrows {
Кажется, я этот блок уже видела выше и даже отписала к нему комменты
Не дублируй стили

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +    background: center / cover;
а где no-repeat?

2020-03-22 10:14 UTC, crueltycute commented on static/js/views/indexView/indexView.tmpl.xml
> +                <img class="main-slider__arrows_left" src="/static/img/left-arrow.svg"/>
svg (если не очень длинные) можно вставлять прямо в html
Тут ты мог бы либо прописать div class="main-slider__arrows_left" и внутрь вставить svg, либо сразу svg class="main-slider__arrows_left"
img использовать не любят как-то

2020-03-22 21:12 UTC, DronBrigadir commented on static/js/views/indexView/indexView.scss
> +  height: 48vw;
потому что картинка широкоформатная и если экран будет как на мобиле длинный и узкий то ее растянет не пол экрана

2020-03-22 21:13 UTC, DronBrigadir commented on static/js/views/indexView/indexView.scss
> +  margin-bottom: -8%;
ну так клево же )

2020-03-23 13:18 UTC, DronBrigadir commented on static/js/views/indexView/indexView.scss
> +      &:hover {
так не делается, их начинает сразу две дергать при ведении

2020-03-23 13:24 UTC, DronBrigadir commented on static/js/views/indexView/indexView.scss
> +  &__bottom-shade {
так position не наследуется же, а все остальные разные, кроме bottom

2020-03-23 13:30 UTC, DronBrigadir commented on static/js/views/indexView/indexView.scss
> +      text-align: justify;
а можно чем-нибудь заменить, чтобы он по ширине выравнивался или просто поставить выравнивание по левому краю?

2020-03-23 14:41 UTC, DronBrigadir commented on static/js/views/indexView/indexView.tmpl.xml
> +                <img class="main-slider__arrows_left" src="/static/img/left-arrow.svg"/>
вставил прямо в html только в верхнем слайдере, в маленьких слайдерах оставил так, потому что их может быть много и получается в каждый слайдер срендерится svg и html большой будет

2020-03-23 19:18 UTC, n-merkulova requested changes

2020-03-23 19:18 UTC, crueltycute commented on static/css/button.scss
> +@mixin gradientButton {
можно не создавать отдельный файл для одного миксина кнопки, а вынести в общий файл mixins.scss

2020-03-23 19:18 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +  height: 48vw;
тогда для такого лучше использовать не vw, а em или rem

2020-03-23 19:18 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +  height: 48vw;
или пиксели, опять же
и медиа запросы

2020-03-23 19:18 UTC, crueltycute commented on static/js/views/indexView/indexView.scss
> +      repeat: no-repeat;
для этого есть супер-короткая запись `background: no-repeat center 0 / cover`

2020-03-24 10:28 UTC, merged