List view
frontend-park-mail-ru/2020_1_k-on pull request #32
Opened 2020-03-21 23:18 UTC by AliceSitedge

2020-03-22 09:40 UTC, n-merkulova requested changes

2020-03-22 09:40 UTC, n-merkulova commented on static/js/libs/api.js
> +        console.log(filtersString);
забыла console.log, их лучше не оставлять

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.js
> +        arrow.style.transform = 'rotateZ(0)';
Анимацию на стрелочку можно наложить сразу в css, не используя js

`.filter-button__arrow {`
`  transform: rotateZ(180deg);`
`  opacity: 1;`
`  visibility: visible;`
`  transition: 0.15s linear`
`  &_active {`
`    transform: none;`
`    opacity: 0;`
`    visibility: hidden;`
`    }`
`  }`

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.js
> +        this.data.chosenFilters = {
Дефолтные значения фильтров надо вынести в константы

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.js
> +        Api.getList(this.type, {
Вот возможный вариант, как лучше поступить со списком
Создаешь отдельный компонент, кладешь его в components
Он будет уметь сам ходить на бэк за списком фильмов/сериалов (то есть будет, скажем, метод getData, который будет вызывать вот этот метод Api.getList)

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.js
>          super.render(root);
Здесь, в конструкторе, ты инициализируешь этот компонент (у него есть как раз те дефолтные значения фильтров, которые я сказала вынести в константы, так что ничего не передаешь в него пока) и вызываешь его рендер
Он с дефолтными параметрами фильтров ходит на бэк, получает данные, рисует их

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.js
> +        this.render(this.root);
А вот здесь, когда значения фильтров поменялись, ты вызываешь какой-то метод компонента списка, который сеттит новое значение (например, сделать методы setYear, setGenre, setRating, что будет удобно, если у нас будут разные комбинации сортировок)
После этого в твоем компоненте списка должно срабатывать что-то типа события onParameterChanged, которое с новыми параметрами фильтров вызовет новый запрос на бэк и перерисовку компонента с новыми данными

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.scss
> +      transition: transform 0.2s;
Кстати, вот тут замечание
transition отработает только при наведении курсора
Если убрать курсор, возвращение к исходному состоянию будет без transition
Решается вынесением transition над :hover

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.scss
> +    color: $card-content-color;
Мне, честно говоря, кажется, что лучше сделать не акцентным желтым цветом, я белым с opacity около 0.6
Ну то есть светло-серым, да... Сори, я говорю на языке css лучше, чем на русском...
И еще я бы либо поставила запятые (2018, США, Боевики), либо добавила бы описание (Год: 2018 Страна: США Жанр: Боевики). Но тут хз, не знаю, как будет выглядеть лучше

2020-03-22 09:40 UTC, crueltycute commented on static/js/views/listView/listView.scss
>  .filter-button {
Еще мне кажется, что на кнопке фильтров желтым цветом можно не заливать текст на ховер и фокус, оставить его белым
Посмотри, мб будет прикольнее

2020-03-22 19:18 UTC, AliceSitedge commented on static/js/views/listView/listView.scss
> +    color: $card-content-color;
Хд

2020-03-23 00:22 UTC, AliceSitedge commented on static/js/views/listView/listView.scss
>  .filter-button {
Вроде прикольно

2020-03-23 09:49 UTC, n-merkulova approved these changes

2020-03-23 15:10 UTC, merged